environment:
    GNU_MIRROR: "http://ftp.gnu.org/pub/gnu"

    ARCH:            "$(host-arch)"
    AUTOCONF_BUILD:  "$(host-autoconf)"
    AUTOCONF_HOST:   "$(host-autoconf)"
    MULTIARCH_BUILD: "$(multiarch,$(host-autoconf))"
    MULTIARCH_HOST:  "$(multiarch,$(host-autoconf))"

    BASEMENT_OPTIMIZE: "s"
    BASEMENT_DEBUG: "1"

include:
    - user
