environment:
    GNU_MIRROR: "http://ftp.gnu.org/pub/gnu"

    AUTOCONF_BUILD:  "$(host-autoconf)"
    AUTOCONF_HOST:   "$(host-autoconf)"

    # default compile flags
    BASEMENT_OPTIMIZE: "s" # compiler optimization level (0/1/2/s)
    BASEMENT_DEBUG: "1"    # generate debug symbols (0/1)

archive:
    backend: http
    url: http://ci.bobbuildtool.dev/artifacts/
    flags: [download]

include:
    - user
