inherit: ["python3::flit"]

metaEnvironment:
    PKG_VERSION: "1.6.1"
    PKG_LICENSE: "MIT"

checkoutSCM:
    scm: url
    url: ${GITHUB_MIRROR}/pypa/build/archive/refs/tags/${PKG_VERSION}.tar.gz
    digestSHA256: 3f86cc69a22d5e0a45783be999ee49aad36181ab2be62300d98b4584c26d721f
    stripComponents: 1

depends:
    - python::packaging
    - python::pyproject-hooks
    - python::wheel

buildScript: |
    python3BuildFlit $1

packageScript: |
    python3PackageTgt

provideDeps: ['python::*']
