buildTools: [pkg-config]
buildScript: |
    # make sure to not search any system paths
    export PKG_CONFIG_DIR=

    # gather pkg-config paths
    export PKG_CONFIG_LIBDIR=
    for i in "${@:2}" ; do
        if [[ -d "$i/usr/lib/pkgconfig" ]] ; then
            PKG_CONFIG_LIBDIR="${PKG_CONFIG_LIBDIR:+${PKG_CONFIG_LIBDIR}:}$i/usr/lib/pkgconfig"
        fi
    done
