# Eagerly inherit libtool beause it defines a checkoutScript and will be
# inherited by the autotools class anyway. This prevents a separate checkout
# for the aclocal multiPackage which does not depend on the autotools class.
inherit: [libtool, patch]

metaEnvironment:
    PKG_VERSION: "0.29.1"

checkoutSCM:
    scm: url
    url: https://pkg-config.freedesktop.org/releases/pkg-config-${PKG_VERSION}.tar.gz
    digestSHA1: "271ce928f6d673cc16cbced2bfd14a5f2e5d3d37"
    stripComponents: 1

checkoutDeterministic: True
checkoutScript: |
    patchApplySeries $<<pkg-config/*.patch>>

multiPackage:
    "":
        inherit: [autotools]

        depends:
            - libs::glib-dev

            - use: []
              depends:
                - libs::glib-tgt

        buildScript: |
            export GLIB_CFLAGS="-I${BOB_DEP_PATHS[libs::glib-dev]}/usr/include/glib-2.0"
                   GLIB_CFLAGS+=" -I${BOB_DEP_PATHS[libs::glib-dev]}/usr/lib/glib-2.0/include"
            export GLIB_LIBS="-lglib-2.0 -lpthread"
            autotoolsBuild $1 \
               --disable-host-tool \
               --enable-define-prefix

        packageScript: |
            autotoolsPackageTgt

        provideDeps: [ "*-tgt" ]

    tool:
        inherit: [autotools]
        buildScript: |
            if cpackageCrossCompiling ; then
                export ac_cv_func_posix_getgrgid_r=yes
                export ac_cv_func_posix_getpwuid_r=yes
                export glib_cv_stack_grows=no
                export glib_cv_uscore=no
            fi
            autotoolsBuild $1 \
               --disable-host-tool \
               --with-internal-glib \
               --enable-define-prefix
        packageScript: |
            autotoolsPackageTgt
        provideTools:
            pkg-config: usr/bin

    # Special crafted multiPackage that does not depend on the target toolchain
    # and that provides the aclocal files for automake.
    aclocal:
        buildVars: [PKG_VERSION]
        buildScript: |
            mkdir -p usr/share/aclocal
            sed -e "s/@VERSION@/$PKG_VERSION/" \
                "$1/pkg.m4.in" > usr/share/aclocal/pkg.m4
        packageScript: |
            cp -a "$1"/* .
