name: pre-commit
description: Run pre-commit check
"on": [push, pull_request]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup pre-commit
              run: python -m pip install pre-commit

            - name: Cache pre-commit state
              uses: actions/cache@v4
              with:
                  path: ~/.cache/pre-commit
                  key: "pre-commit|${{ env.pythonLocation }}|\
                        ${{ hashFiles('.pre-commit-config.yaml') }}"

            - name: Run pre-commit
              run: pre-commit run --color=always --all-files
